title: My Portfolio
name: Morgan Fowler
email: morganafowler@hotmail.com
baseurl: "/my-portfolio/"

instagram: "https://www.instagram.com/thefontsnob/"

collections: 
design: 
output: true
permalink: /designs/:name/